version: '3'
services: 
  server:
    container_name: chat-demo-server
    restart: always
    build: ./chat-demo-server
    ports: 
      - '8181:8181'
  client:
    container_name: chat-demo-client
    restart: always
    build: ./chat-demo-client
    ports: 
      - '4200:4200'
    links: 
      - chat-demo-server