version: '3'
services: 
  mongodb:
    image: mongo:3.2.4
    container_name: mongodb
    ports:
      - '27017:27017'    
    command: --smallfiles
      
  server:
    image: naveenkumashi/chat-demo-server
    container_name: chat-demo-server
    restart: always
    build: ./chat-demo-server
    ports: 
      - '8080:8181'
    links: 
     - mongodb
      
  client:
    image: naveenkumashi/chat-demo-client
    container_name: chat-demo-client
    restart: always
    build: ./chat-demo-client
    ports: 
      - '4200:4200'
    links: 
      - server